### PR TITLE
fix(collectionReady): fix bluebird warning

### LINKED ISSUE #214: Bluebird warning
```
    "connect-mongo": "^1.1.0",
    "bluebird": "^3.3.1",
```

After every request I see in my log stacktrace including:

```
Warning: a promise was created in a handler but was not returned from it
    at MongoStore.set (./node_modules/connect-mongo/src/index.js:240:18)
    at Session.save (./node_modules/express-session/session/session.js:71:25)
    at Session.save (./node_modules/express-session/index.js:331:15)
```

I think it's better to fix it on connect-mongo level.

Thanks.

### PR DESCRIPTION
**Pull request by Awk34**
fixes #214

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Can you just explain why it produces a different behavior?
Thx!

**Comment by Awk34** [comment]
To the best of my knowledge, it has to do with Bluebird making sure that your original reference to the created promise is also returned. When you conditionally set it the the property on `this`, it gets confused and thinks that you're not returning the original promise.

**Comment by Awk34** [comment]
During my tests it seems to have fixed the issue.

**Comment by Awk34** [comment]
Here's the relevent Bluebird code:

https://github.com/petkaantonov/bluebird/blob/d62e20741eb759a50aa7af13c5dc7fb2bfbf2694/src/promise.js#L517-L549
```js

Promise.prototype._settlePromiseFromHandler = function (
    handler, receiver, value, promise
) {
    var bitField = promise._bitField;
    if (BIT_FIELD_CHECK(IS_CANCELLED)) return;
    promise._pushContext();
    var x;
    if (receiver === APPLY) {
        if (!value || typeof value.length !== "number") {
            x = errorObj;
            x.e = new TypeError("cannot .spread() a non-array: " +
                                    util.classString(value));
        } else {
            x = tryCatch(handler).apply(this._boundValue(), value);
        }
    } else {
        x = tryCatch(handler).call(receiver, value);
    }
    var promiseCreated = promise._popContext();
    bitField = promise._bitField;
    if (BIT_FIELD_CHECK(IS_CANCELLED)) return;

    ASSERT(!promise._isFateSealed());

    if (x === NEXT_FILTER) {
        promise._reject(value);
    } else if (x === errorObj) {
        promise._rejectCallback(x.e, false);
    } else {
        debug.checkForgottenReturns(x, promiseCreated, "",  promise, this);
        promise._resolveCallback(x);
    }
};
```
https://github.com/petkaantonov/bluebird/blob/5bffd55f20f1df5361603612867f286fa13e56e3/src/debuggability.js#L398-L410
```js
function checkForgottenReturns(returnValue, promiseCreated, name, promise,
                               parent) {
    if (returnValue === undefined && promiseCreated !== null &&
        wForgottenReturn) {
        if (parent !== undefined && parent._returnedNonUndefined()) return;
        if (BIT_FIELD_READ(LENGTH_MASK, promise._bitField) === 0) return;

        if (name) name = name + " ";
        var msg = "a promise was created in a " + name +
            "handler but was not returned from it";
        promise._warn(msg, true, promiseCreated);
    }
}
```

**Comment by Awk34** [comment]
@jdesboeufs do you have any time to look at this? The bluebird warning is still annoying me and I don't want to have to fork this module XD

**Comment by jdesboeufs** [comment]
Published as `v1.2.1`. Thx!!

**Pull request merged**
