### PR TITLE
update dependencies and affected code

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This allows it to build using all of the new dependencies. The reason for this a lot of the dependencies are really really old.

I wasn't sure if the version number should be bumped or if anything else needed to be added/changed.
All tests pass, this was tested on `node v5.0.0`.

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Thank you!
I will release `v1.0.0` before the end of the week.

**Comment by OmgImAlexis** [comment]
Sounds good. :+1: I noticed it decreased the code coverage, I'm assuming that's just from adding extra lines as it was only 0.4%?

**Comment by jdesboeufs** [comment]
No problem with code coverage ;)

**Comment by OmgImAlexis** [comment]
I completely overlooked this but you should probably add v5 to travis since it's been updated to work with it now.

**Comment by erebel55** [comment]
Thanks for the pull :)

**Comment by jdesboeufs** [comment]
Fixed in d09953c4a1ab8ee49c211b472fd9d03f0859932a.
Landing ;)

**Pull request closed without merging**
