### PR TITLE
removing the lastModified prop from the session object before update

### PR DESCRIPTION
**Pull request by rafaelcardoso**
I just realized that I was accidentally setting the `lastModified` prop at the session object, this commit solve this mistake.

### CODE REVIEW

**Comment by jdesboeufs** [comment]
And if a developer want to store a `lastModified` property in the session? :)

**Comment by rafaelcardoso** [comment]
The `lastModified` property will be accessible at the document level, this bug was duplicating the property (at document level and inside de session prop).

**Comment by rafaelcardoso** [comment]
If the developer want to store the `lastModified` property inside the session we will have this data duplicated :s

**Comment by rafaelcardoso** [comment]
There is something wrong with this PR? It's been a few days which is open :disappointed:

**Comment by ilanbiala** [comment]
@jdesboeufs any update on this PR?

**Pull request merged**
